name: Test File Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-upload:
    runs-on: ubuntu-latest

    services:
      docker:
        image: node:16
        ports:
          - 3000:3000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: |
        bun install

    - name: Start the server
      run: |
        bun start &
        sleep 10  # Ensure the server has enough time to start

    - name: Run upload test
      run: |
        echo "This is a test file." > test.txt
        curl -X POST "http://localhost:3000/api/v1/upload" \
        -F "file=@test.txt" || (echo "Upload test failed" && exit 1)
