name: Test File Upload for Multiple File Types

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

jobs:
  test-upload:
    runs-on: ubuntu-latest

    services:
      docker:
        image: node:16
        ports:
          - 3000:3000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: |
        bun install

    - name: Install LibreOffice (for file conversion)
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice

    - name: Start the server
      run: |
        bun start &
        sleep 10  # Ensure the server has enough time to start

    - name: Create test files
      run: |
        echo "This is a test text file." > test.txt
        soffice --convert-to pdf test.txt
        libreoffice --headless --convert-to docx test.txt
        libreoffice --headless --convert-to pptx test.txt

    - name: Test PDF upload
      run: |
        if curl -X POST "http://localhost:3000/api/v1/upload" -F "file=@test.pdf"; then
          echo "PDF Upload SUCCESS"
        else
          echo "PDF Upload FAILURE" > test-output-pdf.log
          exit 1
        fi

    - name: Test DOCX upload
      run: |
        if curl -X POST "http://localhost:3000/api/v1/upload" -F "file=@test.docx"; then
          echo "DOCX Upload SUCCESS"
        else
          echo "DOCX Upload FAILURE" > test-output-docx.log
          exit 1
        fi

    - name: Test PPTX upload
      run: |
        if curl -X POST "http://localhost:3000/api/v1/upload" -F "file=@test.pptx"; then
          echo "PPTX Upload SUCCESS"
        else
          echo "PPTX Upload FAILURE" > test-output-pptx.log
          exit 1
        fi

    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: upload-test-outputs
        path: |
          test-output-pdf.log
          test-output-docx.log
          test-output-pptx.log
          test.pdf
          test.docx
          test.pptx
